### PR TITLE
Update bower.json with current version 1.4.4

### PR DESCRIPTION
**Pull request by clamstew**
* current version 1.4.4 found in src/Scripts/jquery.fileDownload.js
* update bower.json name attr to the name found on the bower.io registry for this repo
* remove a trailing whitespace in README.md

### CODE REVIEW

**Comment by johnculviner** [comment]
thank you sir!

**Comment by clamstew** [comment]
@johnculviner I think the last step is to tag that commit with `1.4.4` and `git push` the tag (so it shows up on https://github.com/johnculviner/jquery.fileDownload/releases).  Can you do that on your end?  I appreciate it.

**Comment by johnculviner** [comment]
right on, give it a shot now

**Comment by clamstew** [comment]
You rock!

**Comment by clamstew** [comment]
it worked

**Comment by johnculviner** [comment]
no problem! if you see any issues or want to make any enhanchments to this let me know and I'll take any PRs you have. I don't really use any jQuery or C# anymore so this is a bit of a legacy thing... (maybe ill switch it to a simple node demo at some point....)

**Comment by clamstew** [comment]
You know, I actually made a node version a bit back to work with grunt connect locally, and I don't think I did much with it.  Let me see if I can put together a PR with it for a node version on the BE.

**Comment by johnculviner** [comment]
Cool! Yeah I think the man reason why I hadn't was I have hardlinks all over the net for the demo to apphb which is ms only tied to the github repo builds. Could probably think of some clever way to redirect. Don't feel too pressured because there will be some refactoring to get it right. Thanks!

**Pull request merged**
